### ISSUE TITLE
Little Bug

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#1]
I cant tell bug but i can show this with video

video coming soon

**Comment by openbullet** [comment]
Please upload the video somewhere and link it here, thanks.

**Comment by openbullet** [comment]
Are you still alive?

**Comment by Teals53** [comment]
oh shit im forgot this sorry nigg i upload video tomorrow lol im lazy xd

**Comment by Teals53** [comment]
https://youtu.be/m3XwfLUeo3I

**Comment by Teals53** [comment]
@openbullet sory for delay im lazy xD

**Comment by Teals53** [comment]
btw its offical ? https://github.com/ForlaxPy/openbullet-1.2/releases

and how i downloand this  tool i dont see any link in githup project or website

**Comment by openbullet** [comment]
No that version is not made by me hence it's not official. To download this project you can google OpenBullet 1.0.0 or compile it yourself. Anyways your issue was fixed here https://github.com/openbullet/openbullet/commit/1e294108214c31b23f457d4f20ae58754632bac4 and it will be included in the 1.0.1 version that I will release shortly.

**Comment by Teals53** [comment]
i show u two bug u fixed last one ?

**Comment by Teals53** [comment]
second bug still alive in 1.0.1 @openbullet

**Comment by Teals53** [comment]
@openbullet second one still alive nigg xd

**Comment by Teals53** [comment]
i just up this issues bcs i dont want open new issues :3

**Comment by openbullet** [comment]
Open a new issue!!!

**Comment by Teals53** [comment]
Fappa
