### ISSUE TITLE
[BUG] small bugs

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#115]
**Describe the bug**
Some small bugs

**To Reproduce**
1. PRINT <List[*]> --> Only Print the first element (<List[0]>)

2. FUNCTION Length "<COOKIES(cookieX)>" --> if the cookieX exists: all is good, if it does not exist: it return 19 (which is the length of the string : <COOKIES(cookieX)> )
3. Save as SET VAR "cookiex" "<COOKIES(cookieX)> "

**Expected behavior**
for PRINT -> Not that important
for second bug, maybe you can make return EMPTY, would be good

**Version**
 - Version [e.g. 1.0.1]

**Reminder**
can u add the DoesNotExist

**Comment by openbullet** [comment]
1. That's not a bug, it was never meant to work XD
2. Well yeah you should check if it exists first, that is the correct behaviour. Otherwise I'd need to return empty even when <div> doesn't get replaced with a variable called div. Many HTML or XML use cases will behave very weirdly. Just do the check first.
3. I didn't quite understand

**Comment by ReDDOOne** [comment]
as for "3." it was the same as "2."
thank you for your answer

again, can you add DoesNotExist lol
thank you ^_^

**Comment by openbullet** [comment]
Done
