### ISSUE TITLE
[REQUEST] Jump FUNCTION

### ISSUE THREAD

**Issue by beer14** [openbullet/openbullet#121]
Hi, you can add FUNCTION block Jump ? like Blackbullet ? 

And i have an other question, how can I update the latest version, knowing that I build the source code myself, I'm tired of starting from scratch and losing all my hits, when I build, I have to change which file to have OB updated?

thanks

**Comment by openbullet** [comment]
No I won't add that function, I removed it for a reason, adding it would result in inconsistencies within the code base and two ways to do the same thing. Use an IF - ELSE construct in LoliScript, please look at the LS documentation inside the program itself.
To update just open git bash, navigate to the folder with the solution file and write "git pull". Then simply rebuild the solution. I use OB directly from the Release folder so that every time I compile it, it's automatically up to date!
