### ISSUE TITLE
[BUG] CapMonster Solution for Normal Captcha Images

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#155]
**Describe the bug**
Here is the solution for the CAPMONSTER with Normal Captcha Images

**To Reproduce**
Use this Config:
https://pastebin.com/raw/3dq177kp

**Screenshots**
with url encode
<img width="2035" alt="Screen Shot 2019-05-01 at 11 18 04 AM" src="https://user-images.githubusercontent.com/23710158/57013391-3f0c8e80-6c03-11e9-80c3-aac09e0f0aec.png">
<img width="2036" alt="Screen Shot 2019-05-01 at 11 18 36 AM" src="https://user-images.githubusercontent.com/23710158/57013397-46339c80-6c03-11e9-8f18-21d3474cbeee.png">

when i disable url encode, i get error
<img width="2031" alt="Screen Shot 2019-05-01 at 11 19 09 AM" src="https://user-images.githubusercontent.com/23710158/57013380-2f8d4580-6c03-11e9-9161-e4a91fd91531.png">

**Version**
 - Version [e.g. 1.1.1]

**Additional context**
I tested this with XEVIL, it is working also
so nothing is needed 

**Request**
i don't see from where we can control different kind of images
i am talking about those params
phrase= / regsense= / numeric= / calc=
min_len= / max_len= / language=

**Comment by openbullet** [comment]
Oh so basically I just have to URLencode the base64 payload in the POST request and it will work?

**Comment by openbullet** [comment]
Also those parameters are specific to every captcha services, so I cannot generalize them for 1 block as different services will support different features.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/fe6277d6f474ea9e3b0e283db7de40cf7595d197 let me know if it works, thank you a lot for your help! You are contributing a lot :)

**Comment by ReDDOOne** [comment]
@openbullet 
the good news, the bug is solved. you can close all capmonster issues

back to those params, they are boolean, so i guess it is easy to add to the app
and the user will choose what he want
so we can have a good rating

**Comment by openbullet** [comment]
The fact is, let's say I implement a checkbox inside the block that says "numeric" so that 2captcha understands if it's a numeric captcha or not.

The person who makes the config CANNOT KNOW if the user will end up using 2captcha or another service, and if that service doesn't support that option it will not be sent and the config might not work as intended.

If I instead implement let's say a selector inside the block that lets you select options basing on the service that is used, I am basically binding captcha solving services to blocks, and it's not a good thing since services might be added or removed over time and they should NEVER be defined inside a block.

How do you think it's best to approach this?
