### ISSUE TITLE
[BUG] When trying to copy with CTRL+C

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#158]
**Describe the bug**
When trying to copy with CTRL+C from debugger log, gets part of C# code

**To Reproduce**
1. Go to stacker for debug
2. Run some config
3. Mark text from debugger log and try to copy with CTRL+C
4. Would copy part of config instead log

Looks like

```{"$type":"System.Collections.Generic.List`1[[RuriLib.BlockBase, RuriLib]], mscorlib","$values":[{"$type":"RuriLib.SBlockElementAction, RuriLib","Locator":5,"ElementString":"//*[@id=\"dwfrm_orders\"]/ul/li/div[2]/div[2]/div[3]","ElementIndex":0,"Action":5,"Input":"","OutputVariable":"","IsCapture":true,"Recursive":false,"Label":"ELEMENT ACTION","Disabled":false}]}```

**Expected behavior**
Copy Log instead code of config

**Version**
 - Version 1.1.1

**Comment by openbullet** [comment]
It's not C# code, it's a json-encoded block. It should only activate that feature when you are NOT copying from a textbox, so I don't know why it's triggering. This bug happens only to a handful of people, it would be nice to know your operative system please.
The only thing I could do is make a setting to disable the blocks copy-paste features so that you and the few others who are experiencing this can solve the issue.

**Comment by mastercho** [comment]
Windows 10 last update

**Comment by mastercho** [comment]
Tried to debug but can't find what causes it, it's pretty annoying lol

**Comment by openbullet** [comment]
Basically the event inside Stacker that catches the Ctrl+C (on your pc, not mine, weirdly) has priority on the event inside the Textbox that catches the same thing. For some reason. I will add a setting as I said.

**Comment by mastercho** [comment]
Will Copy paste disable will effect CTRL+S ?

**Comment by openbullet** [comment]
No it will just disable the ability to Ctrl+C ad Ctrl+V blocks, which is pretty useless if you ask me since you can just copy and paste the LS code ^_^

**Comment by openbullet** [comment]
Added
