### ISSUE TITLE
[BUG] Selenium doesn't detect proxy state

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#159]
**Describe the bug**
In selenium config, if website returns ERR_PROXY_CONNECTION_FAILED OB tries to continue with rest steps of config instead of ban or give retry

**To Reproduce**
1. Set low latency proxy in Selenium config
2. Go to stacker apply it and test on selenium config
3. Steps will continue without giving any warning that proxy is dead

**Expected behavior**
To ban or retry if proxy is dead like HTTP wrapper

**Version**
 - Version 1.1.1

**Comment by mastercho** [comment]
Just notice there BAN ON TIMEOUT in navigating, but seems not working 
https://gyazo.com/e39f6532c4e65fc2ad76cea8b33901c4

**Comment by openbullet** [comment]
As far as I know, there is no way to detect universally if a page loaded successfully to the correct website with selenium. It depends from page to page, so it is always good practice to put a keycheck immediately after the Navigate block in order to check you landed on the correct page by verifying that some element appears on the screen or that the <ADDRESS> variable contains the correct thing.
