### ISSUE TITLE
[BUG] CRASH PROGRAM IN DEBUGGER LOG

### ISSUE THREAD

**Issue by Zigoleiro** [openbullet/openbullet#190]
When I make any request and try to view the log, the program crashes.

 - Version 1.1.2

https://www.airbnb.com.br/

Try the request in site, and check.
When you click on log the program will crash

**Comment by openbullet** [comment]
The program just hangs because the response is HUGE. It's normal, it's not a bug. The GUI just has a hard time printing that huge amount of text to the screen so it hangs a bit. Just wait some seconds and it will print it and start working again. This will not happen when you actually run the config since it will not print the text to the GUI but instead it will only be stored inside variables.
