### ISSUE TITLE
[REQUEST] Variables on the fly.

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#205]
**Describe the solution you'd like**
I would like you to add variables on the fly. I mean that if is enabled so the program will pop up a question to choose a key to be used in the config and the key is used by a placeholder. This can help for a lot of things. Hmm i hope you understand me.

**Comment by openbullet** [comment]
OpenBullet already supports this.
Config -> Other Options -> Inputs
Just define an input like
Description: `Which country are you from? (us, de, fr ...)` Variable: `COUNTRY` and then you can use the custom user input inside your code by simply doing `<COUNTRY>` since a variable with that name and the value chosen by the user will be set.
