### ISSUE TITLE
[REQUEST]PBKDF2 Encryption.

### ISSUE THREAD

**Issue by percebal** [openbullet/openbullet#213]
It would be very good to have this type of encryption added to the function in blocks, since many times it is necessary to encrypt your password.

**Comment by deletelist** [comment]
https://i.postimg.cc/QdL29G7N/Cattura.png
esiste/exist

**Comment by meinname** [comment]
I want to vouch for this request.

Best with configureable Iterations, Salt and Hashtype (as I'd need for some config SHA256)
And ofc with optional output in Base64 
All Similar to the HMAC Function with Salt instead of HMAC Key and a field for Iterations.

More about using different Hashtypes than the default SHA1:
https://stackoverflow.com/questions/18648084/rfc2898-pbkdf2-with-sha256-as-digest-in-c-sharp

**Comment by openbullet** [comment]
Done in last refactor

**Comment by percebal** [comment]
i saw you add funtion pbkdf2pkcs5,can you add pbkdf2 whit output hex.

**Comment by openbullet** [comment]
You can use a utility block to convert between base64 and hex.
