### ISSUE TITLE
config converter

### ISSUE THREAD

**Issue by apektos1000** [openbullet/openbullet#22]
how can I convert .ini and .bbc (for blackbullet) to .loli (for bluebullet)
btw guys why you make a copy of blackbullet for no reason?

**Comment by ForlaxPy** [comment]
for now the only way is to re-create the config, unless Ruri the dev of BB add something like a converter, I mean he has everything needed so it would be very great to implement a such feature. As it will be a pain to recode all the configs maybe a little converter tool would do the job, I don't know how bbc were working I could have coded something.

**Comment by kernelzeroday** [comment]
In my closed issue I asked this question and was told a converter exists in the now unavailable paid version of blackbullet. Since my tree now actually builds on a vanilla VS 2017 I am now able to begin addressing this major functionality issue in my tree as my pull request which fixes the missing references required to build was rejected I may simply fork and consider this project to be downstream.

**Comment by openbullet** [comment]
@apektos1000 Closing as it's not strictly related to OpenBullet.
