### ISSUE TITLE
[REQUEST] Wordlists Relative Path

### ISSUE THREAD

**Issue by sondreavik** [openbullet/openbullet#299]
**Is your feature request related to a problem? Please describe.**
When using OpenBullet on multiple machines, i.e. through a Dropbox share the paths for the wordlists won't be correct due to the paths not being relative.

**Describe the solution you'd like**
Implement a _Wordlist_ directory which is relative to OpenBullet in the same manner as the _Configs_ directory, preferably with accompanying _Open Folder_ and _Rescan_ buttons in the wordlists manager.

**Describe alternatives you've considered**
Symbolic linking.
`mklink /D "C:\Users\Jeff\Dropbox\Wordlists" "C:\Users\Rahul\Dropbox\Wordlists"`

**Comment by openbullet** [comment]
Please see here https://github.com/openbullet/openbullet/issues/278
I understand the ease of use it would bring but I don't like having a separation (some lists in the database and some in the folder). Anyways I'll talk this through with the beta testers and if I change my mind I'll let you know.

**Comment by sondreavik** [comment]
@openbullet Also just to clarify per your comment on #274 
> 
> 
> Configs take a very small disk space, while wordlists can be huge, it's better to keep them in separate folders and just store their location in the database. Sorry but I won't do this.

I don't want the wordlists stored inside the database, just a link to them in said relative path. Also, if you meant that the files has to be read in full before they can be added/rescanned then perhaps skip CRC and go by filename instead or automatically append a random integer suffix to the name of any wordlists inside the _Wordlists_ directory.

**Comment by openbullet** [comment]
I understood what you meant, maybe I phrased that wrong. I meant that it's better to keep the folders on their original location and store the full path inside the DB instead of making it like configs where they must be inside a single folder, which can get huge.
Doing both at the same time feels like adding confusion to the codebase for a small gain imho.
Adding / Rescanning is not an issue as it's currently set to just count the lines and read the first one to automatically adjust the Wordlist Type, so there's no issue about that.

**Comment by openbullet** [comment]
Anyways if you want to be able to store relative paths inside the DB instead of only full paths, then I can allow that by automatically recognizing when the target folder for a Wordlist Import is a subfolder of the root OB directory and cut the first part of the path, so that it's stored in the DB as relative.
If you meant that, I will reopen this issue.

**Comment by sondreavik** [comment]
> 
> 
> Anyways if you want to be able to store relative paths inside the DB instead of only full paths, then I can allow that by automatically recognizing when the target folder for a Wordlist Import is a subfolder of the root OB directory and cut the first part of the path, so that it's stored in the DB as relative.
> If you meant that, I will reopen this issue.

Yes please, that'd suffice!

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/f9e3b6f8e8006efc677590e88297726091539c46
