### ISSUE TITLE
[REQUEST] Automatic detection proxy protocol

### ISSUE THREAD

**Issue by ruz0ne** [openbullet/openbullet#302]
it would be a nice enhancement for the proxy checker to detect the proxy protocol automatically. so users like me with thousands of proxys with mixed protocols can use this proxy checker properly. 

also it would be a nice enhancement if the proxy checker can check if the proxy supports post and cookie requests

**Comment by ShadixAced** [comment]
it would mean : 
- testing proxies one by one everytime to check in which way they work (http/socks4(a)/socks5)
or assuming that some ports belong to http, some to socks4(a) and socks5, which is way more complicated because proxy ports can be random and could fit for other proxy protocols.
(eg. port 52142 could work for socks5, but could also work for socks4 or even http)

**Comment by openbullet** [comment]
Sorry I won't do this, too much work. Just use better lists
