### ISSUE TITLE
[REQUEST] Get token by javascript?

### ISSUE THREAD

**Issue by JepsonHerts** [openbullet/openbullet#329]
In a site, the token has been generated by Javascript:
		$(function() {
		var base_str = "djJ8TmZTNTNDYlpTeHlUN0xjY0dXVkZCWUxoVUpSa3U1OHd8RW-_quUmKwyhq782MKd9U43bZkxYTll7gq7GjKfombbT61nN";
		var i = 0;
		while (true)
		{
			hash = md5(base_str + i);
			if (hash.substr(0, 2) == '00')
			{
				break;
			}
			i++;
		}
		$('input[name=token]').val(i);
	});

How can i put this in a variable for request button in post data?
Sorry for my bad english.

**Comment by openbullet** [comment]
First of all, check out this post https://forum.openbullet.dev/topic/13/how-to-execute-javascript-code
Then since the md5 function is probably not defined you will need to copy the code for example from here http://pajhome.org.uk/crypt/md5/md5.html
Otherwise just convert it to block logic and write the loliscript code for it.
