### ISSUE TITLE
[BUG] additional fix drag and drop files

### ISSUE THREAD

**Issue by Zurzar** [openbullet/openbullet#419]
Hello. I ask for an additional fix
https://github.com/openbullet/openbullet/commit/32f623a3b804ef6150474842f87f9ef7af2d243e

If we use URL or NUMERIC combo, drag and drop in form "worldlist", we have anyway type as = UserPass

It would be nice if the program itself could determine the types.

**Comment by openbullet** [comment]
That would be a problem related to your own Environment.ini file.
Have you tried moving the URLs or Numeric wordlist types to the top of your Environment.ini file? Because their regular expressions get checked in order from the first to the last and the first that matches will be the one that is automatically set.
