### ISSUE TITLE
[BUG] Generate Random Key/Code Repetition Bug

### ISSUE THREAD

**Issue by caspertheghost1337** [openbullet/openbullet#472]
For instance, when I put the format for the key to be 2 capital letters and 6 numbers, it'll make them perfectly fine like HD591921, but after a while, it will start making AA000000 over and over until I restart OpenBullet. I do not know how to recreate this, since it happened randomly twice of out four days. The feature request I recently put in was because of this, since I had to restart OpenBullet twice and lose my runners. Thanks!

**Comment by Laiteux** [comment]
Could be due to OpenBullet not actually "locking" its ``BotData#Random``?

https://github.com/openbullet/openbullet/blob/master/RuriLib/Blocks/BlockFunction.cs#L665

https://docs.microsoft.com/en-us/dotnet/api/system.random?redirectedfrom=MSDN&view=netframework-4.8#the-systemrandom-class-and-thread-safety

**Comment by openbullet** [comment]
Yes that's a really good idea, I will add locking to that property then. Thanks!

**Comment by openbullet** [comment]
Nevermind, I just saw your pull request, I will check it and merge it as soon as I can. Thanks!

**Comment by openbullet** [comment]
This should be fixed thanks to @Laiteux 's PR
