### ISSUE TITLE
[BUG] String go byebye on "Exists" keycheck when switching to LoliScript

### ISSUE THREAD

**Issue by Laiteux** [openbullet/openbullet#486]
**Describe the bug**
When selecting the "Exists" comparator and after entering the string to be checked on a key check block, once you switch to LoliScript this is what you get:
```
KEYCHECK
  KEYCHAIN Success OR
    KEY "<COOKIES{*}>" Exists
```
As you can see, the string is gone, and when switching back to stack view it in fact disappeared.

**Expected behavior**
I believe this is what it should look like:
```
KEYCHECK
  KEYCHAIN Success OR
    KEY "<COOKIES{*}>" Exists "csrf_token"
```

**Version**
1.1.5 (Latest when submitting this issue)

**Comment by openbullet** [comment]
The `Exists` options is peculiar, when you read the documentation in the code https://github.com/openbullet/openbullet/blob/master/RuriLib/Functions/Conditions/Condition.cs it says `Whether any variable can be replaced inside the string.`

Basically this condition returns true when any replacement took place when processing the input string (hence why it only needs 1 string parameter and not 2 like all other options) so in your case you would need to type `KEY "<COOKIES(csrf_token)>" Exists`. When there is a cookie with that name, its value will be put inside the string and so a replacement took place and the condition is true, otherwise since no cookie is found with that name the string is untouched and the condition returns false. 

This allows to check if a variable exists e.g. `KEY "<MYVAR>" Exists` and it's not limited to checking if a list or dictionary contains a specific item.
