### ISSUE TITLE
[BUG]Selenium proxy problems

### ISSUE THREAD

**Issue by batonboy** [openbullet/openbullet#497]
As ruri suggested, put the unsolved problem here.

When using browser open with proxies, errors pop up. No any sources or headers information can be captured. Errors look like
===== LOG FOR BOT #2 WITH DATA 0016179174:79174 AND PROXY 101.231.104.82:80 (Http) =====
The Bot Logging is disabled in General Settings
===== BOT TERMINATED WITH RESULT: NONE =====

https://imgur.com/a/DOsm6Nb

**Comment by openbullet** [comment]
Bot Logging is disabled in General Settings only means that logs are not enabled, that is not an error.
The HTTP timeout is probably due to the fact that you killed the chromedriver.exe process while OB was still trying to control the browser. OB and the chromedriver communicate over HTTP locally on your computer and if the chromedriver gets closed, OB's requests will find no one to respond and will timeout. If the issue persists, please provide a reliable way to reproduce it because I can't.
