### ISSUE TITLE
Jump Function not working

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#51]
Whenever I try to Jump to Upper Block .. Bot Ends on Status Error
http://prntscr.com/n9dedg
My UpperBlock Looks Like this.
```
#Test REQUEST POST "https://example.com" AutoRedirect=FALSE 
  CONTENT ".......
   ... ...
   ... ...
```
I got variable like this 
```
Varc (Single) = Checking
link (Single) = data
ITEM (Single) = Terms Of Service
```

Now when I jump to Upper Block .. there is error... please take a look http://prntscr.com/n9dedg
 :)

**Comment by MeowBullet** [comment]
To upper block, lol your not supposed to jump to an upper, your supposed to jump to a lower block.

**Comment by styles977** [comment]
@MeowBullet .. The bot is Capable of Jumping the upper block. There is just some Bugs. I am 100% sure ....
@openbullet  also one more thing .. the JUMP statement can jump to lower Block but not upper one :)

**Comment by MeowBullet** [comment]
@styles977 why the heck are you making it jump to an upper block. There is no point to have it do that. Lower sure... But upper... Like wtaf.

**Comment by styles977** [comment]
@MeowBullet of course many Reason .. For Example
#LABEL Request "www.example.com" 
GET VAR "Random"
IF VAR RANDOM CONTAINS "CHECKING YOUR BROWSER"
BYPASS CF ##execute Bypass CF BLOCK
SET GCOOKIES
JUMP #LABEL
Now no need to bypass CF as long as cookie last.

**Comment by ReDDOOne** [comment]
the function seems to work fine for me

`FUNCTION Constant "200" -> VAR "status" 

#here REQUEST GET "https://httpbin.org/status/<status>" 
  
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" 
  HEADER "Pragma: no-cache" 
  HEADER "Accept: */*" 

IF "<status>" EqualTo "200"

FUNCTION Compute "<status> + 102" -> VAR "status" 

JUMP #here
ENDIF

`

Try this

**Comment by openbullet** [comment]
The function works fine and I cannot see the full script from your screenshot so I cannot help you unless you provide the entire screenshot. Also since you're using EqualTo "data" are you sure inside the link variable there isn't any trailing space or anything like that? I'd try with Contains first.

**Comment by styles977** [comment]
@openbullet  but for Some reason, it's not jumping to UpperMost Block .. Works fine to the 3rd block though ..
please have a look
Working when I Jump 3rd block : http://prntscr.com/n9hz5j
NotWorking when I Jump 1st Block: http://prntscr.com/n9hzim   ----> It's already Printing Hello but why not jumping to 1st block :(

**Comment by styles977** [comment]
@openbullet  ahh Now I Get It .. Bot just couldn't Jump to the Uppermost lines ... If I comment that out it works ..
recommended seeing images ;)
http://prntscr.com/n9i6gm 
http://prntscr.com/n9i6up
Thankyou EveryOne for your Kind reply :)

**Comment by meinname** [comment]
I think the problem is the line of the Jump target.
I noticed when label is in line 10 you jump to line 9.
But if the label is in line 1 it would be 0 which doesn't exist.
Or with pics: 
doesn't work:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/16181408/55793559-7df76a80-5ac3-11e9-8093-cd151b98b987.png">
works:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/16181408/55793603-9cf5fc80-5ac3-11e9-8f1e-98399d73aaaa.png">
