### ISSUE TITLE
[REQUEST] JWT token decode

### ISSUE THREAD

**Issue by aaronD1414** [openbullet/openbullet#512]
Hi,

Can u pls add to openbullet to decode jwt tokens.
Yea I know that alot of jwt tokens are just base64 encoded but the difficult ones are hashed too.

**Comment by openbullet** [comment]
While you can easily decode base64, you can't decode a hash. So no.

**Comment by aaronD1414** [comment]
Can u explain to me how like alot of websites can do it then?

site: https://jwt.io/

Op vr 6 mrt. 2020 om 16:47 schreef openbullet <notifications@github.com>:

**Comment by openbullet** [comment]
As you can see on the website, the sample token is
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```
The first part `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9` is base64, so you parse the first part between the start of the token and the first dot and decode base64.

The second part `eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ` is base64 too, so parse between the 2 dots and decode base64.

The last part `SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c` is a base64-encoded SHA256 HMAC. An HMAC does not contain ANY RELEVANT INFORMATION, it' just a signature that verifies that the token has not been messed with by a middleman. So you don't need to somehow decode that, because you can't and there's no reason to.

**Comment by openbullet** [comment]
If you instead want to GENERATE a JWT, then OpenBullet has an HMAC-SHA256 function that you can use, you'll need to provide the secret password that validates the signature (it's probably in the website's source).

**Comment by aaronD1414** [comment]
Yeah I know the example token is just base64 but look at this token:

eyJhbGciOiJSUzI1NiIsImtpZCI6IkQyMkE5RjVGNEQ5QjA5RUM0QUQxNkIyQzQxQ0JCNzc0RUNCOTg3ODgiLCJ0eXAiOiJKV1QiLCJ4NXQiOiIwaXFmWDAyYkNleEswV3NzUWN1M2RPeTVoNGcifQ.eyJuYmYiOjE1ODM1MzY2MjcsImV4cCI6MTU4MzUzNzgyNywiaXNzIjoiaHR0cDovL2ZhcmZldGNoLmNvbSIsImF1ZCI6WyJodHRwOi8vZmFyZmV0Y2guY29tL3Jlc291cmNlcyIsImFwaSIsImZhYnMiXSwiY2xpZW50X2lkIjoiMTlBQjgzQTM3RDgwNDcxMUFDREJDRkE2NDNGRTQzNUQiLCJjbGllbnRfdWlkIjoiMTAwMDIiLCJjbGllbnRfdGVuYW50SWQiOiIxMDAwMCIsImNsaWVudF9ndWVzdCI6IjUxMjk2OTk0MiIsInNjb3BlIjpbImFwaSIsImZhYnMiXX0.smxi-eTYQ6JGewQ7vuAC-Ab7SqXu6tEdbVDAmtGeQqoSzonhlGXcEtfLXhH_kqT5v9JKP1sYbSlNNMMhama8ge6rSTLJRxVttXaenp_EP3OD_lrSpWzi430zTsyJs6vjQVKGZ--tT12rsDCbK-Z9L1XC5BIfZhCKQxqUs_S35ro4Ccjuk0zkmYhV_gqGO2rL_qm-EUcaQoffjh3kTtfEm73hka_v8mA2GlMZmNMZwBMuufVus2ivJ7nag3Upg7PoRNxHr1WJ822gzmMhfPX6D6cNyl0yf16wOkZzXyy7VJwdmy2hlMNoyfcPS5cejLs0g7biHm73T9i8oelKwp7yUQ

Is it possible to decode this token in OB?




Op za 7 mrt. 2020 om 13:47 schreef openbullet <notifications@github.com>

**Comment by openbullet** [comment]
It's the EXACT SAME as the token above.
The first part (decoded) is this
```
{"alg":"RS256","kid":"D22A9F5F4D9B09EC4AD16B2C41CBB774ECB98788","typ":"JWT","x5t":"0iqfX02bCexK0WssQcu3dOy5h4g"}
```
The second part (decoded) is this
```
{"nbf":1583536627,"exp":1583537827,"iss":"http://farfetch.com","aud":["http://farfetch.com/resources","api","fabs"],"client_id":"19AB83A37D804711ACDBCFA643FE435D","client_uid":"10002","client_tenantId":"10000","client_guest":"512969942","scope":["api","fabs"]}
```

And the last part is the HMAC-SHA256 signature which, as I already explained, cannot be decoded and you don't need to because it doesn't contain any data, it's just for verification purposes.

**Comment by openbullet** [comment]
You cannot just plug the WHOLE thing into a Function -> Base64Decode block! It will not work.
You have to parse the first 2 parts, there are 3 parts in total separated by a dot (`.`) and you have to decode the first 2 parts individually with 2 blocks. So in total 2 parse blocks and 2 function blocks.

**Comment by aaronD1414** [comment]
Ah thx men lol didn't know

Op za 7 mrt. 2020 om 09:27 schreef openbullet <notifications@github.com>:

**Comment by testconfigsur** [comment]
but so when you decrypt the base64 code how did you re-generate a good token jwt
