### ISSUE TITLE
[REQUEST] Delete File and Delete Folder >> Utility Block

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/openbullet#609]
Hi,

Please add DELETE File and DELETE Folder in Utility block

THANKS

**Comment by shlok8749831769** [comment]
NO NO NO PEOPLE CAN MAKE FAKE CONFIGS AND DELETE YOUR PERSONAL DATA! NEVER!

**Comment by Unkn9wn1** [comment]
lol
bro don't scare that much
\+ OpenBullet configs have no Encryption
\+\+ OpenBullet path is limited to the OB Folder

also scare of abuse, should not prevent upgrades and limit a nice program like OB
if the dev was a guy like you-
there was no plugins section and many more features in OpenBullet

**Comment by openbullet** [comment]
@shlok8749831769 the recent changes make it so that all file/folder commands can only be executed inside the working directory of OB so there's no risk whatsoever

**Comment by shlok8749831769** [comment]
> @shlok8749831769 the recent changes make it so that all file/folder commands can only be executed inside the working directory of OB so there's no risk whatsoever

what if they corrupt your OB or delete your hits DB? Make an option in settings "allow configs to delete files in OB Folder"

**Comment by openbullet** [comment]
I think if the file is being used they can't delete it but I haven't tried

**Comment by LeXector** [comment]
@shlok8749831769 You can "ruin" your files already without the delete option. If you choose e.g. the "write" option for a file and choose an important one, all the content in the file will get deleted and the new text will be written into it. So you basically cannot use the file anymore after the "write" operation. Therefore, I dont see an argument to not implement the delete option because the "risk" is already there.
