### ISSUE TITLE
Issue with JSON

### ISSUE THREAD

**Issue by Myztical1** [openbullet/openbullet#62]
`{
   "installation_token" : "MHASqmHjwkxyhFVXcbrD1554621481",
   "license_key" : "6USNA:GU88-3UBB-MW5V-DEPT",
   "tags" : "{\\u000a   \"affiliate_id\" : \"\",\\u000a   \"affiliate_name\" : \"consumer\",\\u000a   \"antivirus\" : [\\u000a      \"Windows Defender\"\\u000a   ],\\u000a   \"biz_env\" : false,\\u000a   \"domain_name\" : \"\",\\u000a   \"is_on_domain\" : false,\\u000a   \"license_state\" : \"trial\",\\u000a   \"os\" : \"Windows 10 Service Pack 1\",\\u000a   \"os_build\" : \"7601\",\\u000a   \"unredeem_reason\" : \"\",\\u000a   \"user_is_admin\" : false\\u000a}"
}`
https://imgur.com/emchEV0.png

**Comment by openbullet** [comment]
Thanks. Explanation to any reader who doesn't know why this is an issue:
When this particular string `\"` gets converted into LoliScript, the writer will escape the " and hence write `\\"` which will cause a mess when converted back to Blocks.

**Comment by shdf2** [comment]
Well i found a workaround, first do a Replace function to remove that annoying \
and then do your Parse/catpures.

**Comment by shdf2** [comment]
The workaround is not working, the Replace function doesn't like the \\ char
i'm going crazy with this !

**Comment by shdf2** [comment]
Another config i'm trying to do is once again fucked up because of escaping chars not working...
i have to add this in my custom Headers : 
`If-None-Match: W/"5cb07e63-418"`

Result is : 
![image](https://user-images.githubusercontent.com/37487684/56415692-b864c280-628e-11e9-813f-8042e8f6aca7.png)

and here is what happens in loliscript :
![image](https://user-images.githubusercontent.com/37487684/56415716-d8948180-628e-11e9-89bc-58884ba081ee.png)

**Comment by openbullet** [comment]
Done https://github.com/openbullet/openbullet/commit/29180b0165e201af021b404a2362debfe119de7b
