### ISSUE TITLE
 ERROR: The format of the input string is incorrect.

### ISSUE THREAD

**Issue by ronnie32** [openbullet/openbullet#66]
Hi,
When debugging I'm getting "ERROR: The format of the input string is incorrect." after Key Check, I guess its because I'm running the program on non-US Windows environment?
Could you fix it please?

**Comment by openbullet** [comment]
No it's because as test data you are putting something that is not correct basing on the wordlist type you selected, and if you try to run it in the Runner it will skip that line and not test it. To solve this you can go to the Envrionment.ini file and set Verify=False on the wordlist type you want to use or you can just fix your input data. Closing.

**Comment by ronnie32** [comment]
I have already tried to put the verify variable on false, and same thing, also I've set the wordlist type on Numeric, and its basically a digit chain...
