### ISSUE TITLE
copy paste,and blocks![BUG]

### ISSUE THREAD

**Issue by navidevangel** [openbullet/openbullet#689]
hey
there is some bugs
first is
sometimes when i use recaptcha block,when it solve recaptcha it get end and its dont continue and going for next block

also
when i use Ctrl+A and i copy anything,when i want paste it it paste just some ------- or some {}{}P{ and..

**Comment by openbullet** [comment]
The first might be caused by the fact that when you select a block while the debugger is running, it picks that block as the current block so if you select the last block it will think that it ended processing. Please do not touch blocks while the debugger is running unless you want this behaviour to happen.

For the second I have no idea how to replicate it, please provide more info on how to replicate the issue consistently

**Comment by navidevangel** [comment]
more info: if any detail make copy by "Ctrl+c " it wont get copy,just
should copy it by click right and selecting copy

**Comment by openbullet** [comment]
have you tried the setting "disable CTRL+C/V in blocks"? Try to see if it works for you.

**Comment by openbullet** [comment]
Because when you do CTRL C sometimes the block gets copied instead of the thing you actually want to copy

**Comment by navidevangel** [comment]
yes i tried but no difference,even if want copy from source it happen to,in
blocks too,in last versions its hadnt this problem
