### ISSUE TITLE
ERROR: Failed to receive the response from the HTTP-server openbullet

### ISSUE THREAD

**Issue by lixox-lox** [openbullet/openbullet#807]
I get this erroe while trying to use some configs.
P.S I tried VPN and such things but it still show this error.
Any solution?

**Comment by openbullet** [comment]
Sorry OB1 is not supported anymore, switch to OB2.
Also this error is very generic, maybe the endpoint changed or it could also be the http proxies. Go to the debugger and debug the config manually, maybe use fiddler to see what happens or try to open the URL of the request in chrome and see what pops up.

**Comment by lixox-lox** [comment]
Hey
Tnx for the fast feedback.
I tried the openbullet2 but firstly it doesnt open.
Secondly does it support the configs made with openbullet1?

**Comment by openbullet** [comment]
> I tried the openbullet2 but firstly it doesnt open.

You need to install the asp.net core runtime (or the .net sdk if you prefer) otherwise it will not open. Please follow this guide https://discourse.openbullet.dev/t/how-to-download-and-start-openbullet-2/29

> Secondly does it support the configs made with openbullet1?

No, you have to rebuild the config, but the blocks are very similar so unless you have some complex loliscript logic it will be easy to translate the config to the new format.
