### ISSUE TITLE
[BUG] Have to delete Database to open OpenBullet.

### ISSUE THREAD

**Issue by TheThirdGender** [openbullet/openbullet#823]
Hello,

I've been having this glitch for a few months now where I have to delete my database about once a week in order to open OpenBullet.

OpenBullet simply doesn't open once I try to run the Openbullet.exe file. There are no error messages anywhere, and it runs in the background ( In Task Manager ) for about 5 seconds before disappearing when I start it.

When I delete the database, it opens perfectly fine.

I have been using a Utility block to save most hits to a Hits folder now, but this has just been bugging me enough to the point where I'd like to see if anyone else has had this issue.

**Comment by openbullet** [comment]
This is a known issue caused by not shutting down OB1 gracefully (i.e. the machine powers off while it's writing hits to the DB).
There is a setting that you can enable to make OB1 write everything to the filesystem instead of the DB, enable that setting, there is no need to write hits to file manually in the config with the utility block.

Also, OB1 is out of support, please switch to OB2 where the DB does not get corrupted.
